/*
 * Copyright (C) 2012 Nexell Co., All Rights Reserved
 * Nexell Co. Proprietary & Confidential
 * 
 * NEXELL INFORMS THAT THIS CODE AND INFORMATION IS PROVIDED "AS IS" BASE
 * AND WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING
 * BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR
 * FITNESS FOR A PARTICULAR PURPOSE.
 * 
 * Module	: Crypto
 * File		: nx_crypto.h
 * Description	:
 * Author	: 
 * History	:
 */
#ifndef __NX_CRYPTO_H__
#define __NX_CRYPTO_H__

#include "nx_prototype.h"

struct NX_CRYPTO_RegisterSet {
	u32 CRYPTO_CRT_CTRL0;
	u32 _Reserved[2];
	u32 CRYPTO_AES_CTRL0;
	u32 CRYPTO_AES_IV[4];
	u32 CRYPTO_AES_CNT[4];
	u32 CRYPTO_AES_KEY[8];
	u32 CRYPTO_AES_TIN[4];
	u32 CRYPTO_AES_TOUT[4];
	u32 CRYPTO_DES_IV[2];
	u32 CRYPTO_DES_KEY[3][2];
	u32 CRYPTO_DES_TIN[2];
	u32 CRYPTO_DES_TOUT[2];
	u32 CRYPTO_CRT_BDMAR;
	u32 CRYPTO_CRT_BDMAW;
	u32 CRYPTO_CRT_HDMAR;
	u32 CRYPTO_HASH_CTRL0;
	u32 CRYPTO_HASH_IV[5];
	u32 CRYPTO_HASH_TOUT[5];
	u32 CRYPTO_HASH_TIN;
	u32 CRYPTO_HASH_MSZE[2];
};

#endif /* __NX_CRYPTO_H__ */
